# Generated by Django 5.0.6 on 2024-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_blog_type_blog_job_role_blog_job_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="blog_type",
            field=models.CharField(
                choices=[("INTERVIEW", "Interview"), ("WORK EXP", "Work Experience")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="job_role",
            field=models.CharField(
                choices=[
                    ("DEV", "Developer"),
                    ("DES", "Designer"),
                    ("MKT", "Marketing"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FT", "Full Time"),
                    ("PT", "Part Time"),
                    ("INTERN", "Internship"),
                ],
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="user_type",
            field=models.CharField(
                choices=[("STUD", "Student"), ("PROF", "Professional")], max_length=4
            ),
        ),
    ]
