# Generated by Django 5.0.6 on 2024-07-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_blog_type_alter_blog_job_role_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="author",
            new_name="user",
        ),
    ]
